config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"

  devise_for :users
  
  resources :users
  resources :categories
  resources :movies do 
    resources :comments
  end
  
  get 'admin', to: 'admin#index'
  get 'admin/index'
  get 'admin/users'
  get 'admin/movies'
  get 'admin/show_movie'
  get 'admin/show_user/:id', to: 'admin#show_user', as: 'admin_user'
  get 'admin/edit_user/:id', to: 'admin#edit_user', as: 'admin_edit_user'
  put 'admin/update_user/:id', to: 'admin#update_user', as: 'admin_update_user'

  namespace :v2 do 
    get 'admin/users'
    get 'admin/movies'
    get 'admin/show_user/:id', to: 'admin#show_user', as: 'admin_user'
    resources :users
    resources :categories
    resources :movies do 
      resources :comments
    end
    resources :comments
  end

  get 'home/index'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, only: [ :create, :update, :destroy ]
  before_action :set_categories, only: [:new, :create, :edit]

  def index
    @movies = Movie.all
  end

  def show
    @comment = @movie.comments.build
  end

  def new
    @movie = Movie.new
  end

  def edit
    authorize @movie
  end

  def create
    
    @movie = current_user.movies.build(movie_params)
    authorize @movie

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @movie
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @movie
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
    end
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def set_categories
    @categories = Category.all.order(:name)
  end 

  # Only allow a list of trusted parameters through.
  def movie_params
    params.require(:movie).permit(:title, :year, :description, :movie_length, :string, :director, :language, :rating, :category_id, :user_id, :image )
  end
end

app/controllers/v2/movies_controller.rb
class V2::MoviesController < ApplicationController
   
  def index
    movies = Movie.all
    render json: movies, each_serializer: MovieSerializer
  end
  
end
  

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
  <%= form.label :year, style: "display: block" %>
  <%= form.text_field :year %>
  </div>


  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :movie_length, style: "display: block" %>
    <%= form.text_field :movie_length %>
  </div>

  <div>
    <%= form.label :director, style: "display: block" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.label :language, style: "display: block" %>
    <%= form.text_field :language %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category_id, options_for_select(@categories.collect{ |cat| [cat.name, cat.id]}) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">

  <p>
    <% if movie.image.present? %>
      <%= image_tag(movie.image, height: '200px') %>
    <% else %>
      <%= image_tag "default-movie.png", height: '200px' %>
    <% end %>
  </p>

  <h2>
    <strong><%= movie.title %></strong>
  </h2>

  <p>
    <strong>Release date:</strong>
    <%= movie.year %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= link_to movie.category.name, movie.category %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= movie.description %>
  </p>

  <p>
    <strong>Movie length:</strong>
    <%= movie.movie_length %>
  </p>

  <p>
    <strong>Director:</strong>
    <%= movie.director %>
  </p>

  <p>
    <strong>Language:</strong>
    <%= movie.language %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= movie.rating %>
  </p>

</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movies</h1>

<div id="movies">
  <% @movies.each do |movie| %>
    <%= render movie %>
    <p>
      <%= link_to "Show this movie", movie %>
    </p>
  <% end %>
</div>

<%= link_to "New movie", new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>
<p>
Comments:
<%= render @movie.comments.order(id: :desc) %>
Add new comment:
<%= render partial: 'comments/form', locals: { movie: @movie } %>


</p>

<div>
  <%= link_to "Edit this movie", edit_movie_path(@movie) if policy(Movie).edit? %> 
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete if policy(Movie).destroy? %>
</div>