config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"

  devise_for :users
  
  resources :users
  resources :categories
  resources :movies do 
    resources :comments
  end
  
  get 'admin', to: 'admin#index'
  get 'admin/index'
  get 'admin/users'
  get 'admin/movies'
  get 'admin/show_movie'
  get 'admin/show_user/:id', to: 'admin#show_user', as: 'admin_user'
  get 'admin/edit_user/:id', to: 'admin#edit_user', as: 'admin_edit_user'
  put 'admin/update_user/:id', to: 'admin#update_user', as: 'admin_update_user'

  namespace :v2 do 
    get 'admin/users'
    get 'admin/movies'
    get 'admin/show_user/:id', to: 'admin#show_user', as: 'admin_user'
    resources :users
    resources :categories
    resources :movies do 
      resources :comments
    end
    resources :comments
  end

  get 'home/index'
end

app/views/admin/_link.html.erb
<%= link_to resource.name.capitalize, url_for([:admin, resource]), class:'btn btn-primary' %>

app/views/admin/_nav_links.html.erb
<div class="container text-center">
    <p>
        <%= link_to "Admin", admin_path %> <%= " / #{params[:action].capitalize}" unless params[:action].eql?("index") %>
    </p>
    <div class="btn-group">
        <%= render "admin/link", resource: Movie %>
        <%= render "admin/link", resource: User %>
    </div>
</div>              

app/views/admin/edit_user.html.erb
<%= form_with(model: @user, url: admin_update_user_path(@user), method: "patch") do |form| %>
    
    <div>
        <%= form.label :status %>
        <%= form.select :status, User.statuses.keys.map{ |key| [key.humanize, key] }, selected: @user.status || :draft %>
    </div>

    <div>
        <%= form.submit %>
    </div>

<% end %>

app/views/admin/index.html.erb
<div class="container">
    <h1 class="text-center">Admin Panel</h1>
    <%= render 'admin/nav_links' %>
</div>

app/views/admin/movies.html.erb
<div class="container">
    <h1 class="text-center">Admin Panel</h1>
    <%= render 'admin/nav_links' %>
</div>

<div id="movies">
  <% @movies.each do |movie| %>
    <%= render movie %>
    <p>
      <%= link_to "Show this movie", movie %>
    </p>
  <% end %>
</div>

<%= link_to "New movie", new_movie_path %>

app/views/admin/show_user.html.erb
<div>
  <p>
    <strong>Login:</strong>
    <%= @user.login %>
  </p>
  <p>  
    <% if @user.avatar.present? %>
      <%= image_tag( @user.avatar, height: '120px', class: "rounded-circle") %>
    <% else %>
      <class="rounded-circle" src="/assets/images/default_avatar.jpg">
    <% end %>
  </p>
  

  <p>
    <strong>About me:</strong>
    <%= @user.about_me %>
  </p>

</div>

<%= render :template => "admin/edit_user" %>

app/views/admin/users.html.erb
<div class="container">
    <h1 class="text-center">Admin Panel</h1>
    <%= render 'admin/nav_links' %>
</div>

<div id="users">
  <% @users.each do |user| %>
    <p>
      <strong>Login:</strong>
      <%= user.login %>
    </p>
    <p>  
      <% if user.avatar.present? %>
        <%= image_tag(user.avatar, height: '120px', class: "rounded-circle") %>
      <% else %>
        <class="rounded-circle" src="/assets/images/default_avatar.jpg">
      <% end %>
    </p>
    <p>
      <%= link_to "Show this user", admin_user_path(user) %>
    </p>
  <% end %>
</div>