config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"

  devise_for :users
  
  resources :users
  resources :categories
  resources :movies do 
    resources :comments
  end
  
  get 'admin', to: 'admin#index'
  get 'admin/index'
  get 'admin/users'
  get 'admin/movies'
  get 'admin/show_movie'
  get 'admin/show_user/:id', to: 'admin#show_user', as: 'admin_user'
  get 'admin/edit_user/:id', to: 'admin#edit_user', as: 'admin_edit_user'
  put 'admin/update_user/:id', to: 'admin#update_user', as: 'admin_update_user'

  namespace :v2 do 
    get 'admin/users'
    get 'admin/movies'
    get 'admin/show_user/:id', to: 'admin#show_user', as: 'admin_user'
    resources :users
    resources :categories
    resources :movies do 
      resources :comments
    end
    resources :comments
  end

  get 'home/index'
end

app/views/layouts/_user_bar.erb
<%= link_to root_path do %>
    <%= image_tag "logo.png", height: '30px' %>
<% end %>

<div class='container'>
<% if current_user %>
    <% if current_user.avatar.persisted? %>
        <%= image_tag current_user.avatar, height: '40px' %>
    <% end %>
    <%= "Logged as #{current_user.login}" %>
    <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
    <%= button_to 'Profile', user_path(current_user), method: :get %>
    <% if current_user.admin? %>
        <%= button_to 'Admin', admin_path, method: :get  %>
    <% end %>
<% else %>
    <%= link_to 'Sign in', new_user_session_path %>
    <%= link_to 'Register', new_user_registration_path %>
<% end %>
    <%= button_to 'Movies Database', movies_path, method: :get %>
</div>

app/views/layouts/application.html.erb
<%= render 'layouts/user_bar' %>
<!DOCTYPE html>
<html>
  <head>
    <title>FilmApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class='container'>
    <%= yield %>
  </div> 
  </body>
</html>